export const MESSAGE_KEY_REDUCER_SAGA = `reducerMessages`;

export const MESSAGE_CALL = `MESSAGE_CALL`;
export const MESSAGE_CALL_SUCCESS = `MESSAGE_CALL_SUCCESS`;
export const MESSAGE_CALL_FAILED = `MESSAGE_CALL_FAILED`;
