import { CHATER_USER_ROOM_REFERENCE } from 'app/consts';

export const USER_ROOM_KEY_REDUCER_SAGA = `reducerUserRooms`;
export const USER_ROOM_CALL = `${CHATER_USER_ROOM_REFERENCE}_USER_ROM_CALL`;
export const USER_ROOM_FAILED = `${CHATER_USER_ROOM_REFERENCE}_USER_ROM_FAILED`;
export const USER_ROOM_SUCCESS = `${CHATER_USER_ROOM_REFERENCE}_USER_ROM_SUCCESS`;

export const ROOM_USER_CALL = `${CHATER_USER_ROOM_REFERENCE}_ROOM_USER_CALL`;
export const ROOM_USER_FAILED = `${CHATER_USER_ROOM_REFERENCE}_ROOM_USER_FAILED`;
export const ROOM_USER_SUCCESS = `${CHATER_USER_ROOM_REFERENCE}_ROOM_USER_SUCCESS`;

export const USER_ROOM_ADD_CALL = `${CHATER_USER_ROOM_REFERENCE}_ADD_CALL`;
export const USER_ROOM_ADDED_FAILED = `${CHATER_USER_ROOM_REFERENCE}_ADDED_FAILED`;
export const USER_ROOM_ADDED_SUCCESS = `${CHATER_USER_ROOM_REFERENCE}_ADDED_SUCCESS`;

export const USER_ROOM_UPDATE_CALL = `${CHATER_USER_ROOM_REFERENCE}_UPDATED_CALL`;
export const USER_ROOM_UPDATED_FAILED = `${CHATER_USER_ROOM_REFERENCE}_UPDATED_FAILED`;
export const USER_ROOM_UPDATED_SUCCESS = `${CHATER_USER_ROOM_REFERENCE}_UPDATED_SUCCESS`;
