import { CHATER_USER_ROOM } from 'app/consts';

export const USER_ROOM_KEY_REDUCER_SAGA = `reducerUserRooms`;
export const USER_ROOM_CALL = `${CHATER_USER_ROOM}_CALL`;
export const USER_ROOM_FAILED = `${CHATER_USER_ROOM}_FAILED`;
export const USER_ROOM_SUCCESS = `${CHATER_USER_ROOM}_SUCCESS`;

export const USER_ROOM_ADD_CALL = `${CHATER_USER_ROOM}_ADD_CALL`;
export const USER_ROOM_ADDED_FAILED = `${CHATER_USER_ROOM}_ADDED_FAILED`;
export const USER_ROOM_ADDED_SUCCESS = `${CHATER_USER_ROOM}_ADDED_SUCCESS`;

export const USER_ROOM_UPDATE_CALL = `${CHATER_USER_ROOM}_UPDATED_CALL`;
export const USER_ROOM_UPDATED_FAILED = `${CHATER_USER_ROOM}_UPDATED_FAILED`;
export const USER_ROOM_UPDATED_SUCCESS = `${CHATER_USER_ROOM}_UPDATED_SUCCESS`;
