export const ROOM_KEY_REDUCER_SAGA = `reducerRooms`;
export const ROOM_CALL = `ROOM_CALL`;
export const ROOM_CALL_FAILED = `ROOM_CALL_FAILED`;
export const ROOM_CALL_SUCCESS = `ROOM_CALL_SUCCESS`;
export const ROOM_CALL_SELECTED = `ROOM_CALL_SELECTED`;
export const ROOM_CALL_SELECTED_SUCCESS = `ROOM_CALL_SELECTED_SUCCESS`;
export const ROOM_CALL_SELECTED_FAILED = `ROOM_CALL_SELECTED_FAILED`;
