import { CHATER_ROOM } from 'app/consts';

export const ROOM_KEY_REDUCER_SAGA = `reducerRooms`;
export const ROOM_CALL = `${CHATER_ROOM}_CALL`;
export const ROOM_FAILED = `${CHATER_ROOM}_FAILED`;
export const ROOM_SUCCESS = `${CHATER_ROOM}_SUCCESS`;
export const ROOM_SELECTED = `${CHATER_ROOM}_SELECTED`;
export const ROOM_SELECTED_SUCCESS = `${CHATER_ROOM}_SELECTED_SUCCESS`;
export const ROOM_SELECTED_FAILED = `${CHATER_ROOM}_SELECTED_FAILED`;

export const ROOM_UPDATE_CALL = `${CHATER_ROOM}_CALL`;
export const ROOM_UPDATED_FAILED = `${CHATER_ROOM}_UPDATED_FAILED`;
export const ROOM_UPDATED_SUCCESS = `${CHATER_ROOM}_UPDATED_SUCCESS`;
